### ISSUE TITLE
Order device list alphabetically

### ISSUE THREAD

**Issue by gerard33** [t0mg/reacticz#15]
Is it possible to order the devices alphabetically in the Device selection?
I have quite some devices, so that could be handy.

I did google on the React sort possibilities, but did not find anything I could understand and implement ;)

**Comment by t0mg** [comment]
You don't need React here :) We want to sort an array of objects by a given propriety, you can use JavaScript's Array.sort with a custom compare function, see for example here http://stackoverflow.com/a/28853839

Ideally the compare function should use both the device type and name strings so that we also get alphabetically ordered categories for free.

**Comment by gerard33** [comment]
Thanks for implementing this!

**Comment by t0mg** [comment]
Sure no problem ;)
