### ISSUE TITLE
Unsupported type: Energy

### ISSUE THREAD

**Issue by pservais** [t0mg/reacticz#39]
{"Battery":255,"RSSI":12,"dtype":"P1 Smart Meter","id":"1","idx":123,"name":"Stroomverbruik","nvalue":0,"stype":"Energy","svalue1":"10606076","svalue2":"5963115","svalue3":"17","svalue4":"13","svalue5":"3430","svalue6":"0","unit":1}

JSON result:
{
   "ActTime" : 1485622018,
   "ServerTime" : "2017-01-28 17:46:58",
   "Sunrise" : "08:19",
   "Sunset" : "17:20",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "Counter" : "16569.889",
         "CounterDeliv" : "0.030",
         "CounterDelivToday" : "0.000 kWh",
         "CounterToday" : "10.240 kWh",
         "CustomImage" : 0,
         "Data" : "10606774;5963115;17;13;3710;0",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 19,
         "HardwareName" : "P1 smartmeter",
         "HardwareType" : "P1 Smart Meter USB",
         "HardwareTypeVal" : 4,
         "HaveTimeout" : false,
         "ID" : "1",
         "LastUpdate" : "2017-01-28 17:46:54",
         "Name" : "Stroomverbruik",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Energy",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "P1 Smart Meter",
         "TypeImg" : "counter",
         "Unit" : 1,
         "Usage" : "3710 Watt",
         "UsageDeliv" : "0 Watt",
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "123"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}

**Comment by t0mg** [comment]
OK so svalue1 to 6 stand for: USAGE1;USAGE2;RETURN1;RETURN2;CONS;PROD
(here: 10606774;5963115;17;13;3710;0)

From Domoticz wiki:
USAGE1= energy usage meter tariff 1
USAGE2= energy usage meter tariff 2
RETURN1= energy return meter tariff 1
RETURN2= energy return meter tariff 2
CONS= actual usage power (Watt)
PROD= actual return power (Watt)

@pservais what information should be displayed by the widget? cons and prod? The energy widget currently looks like this: https://github.com/t0mg/reacticz/wiki/Supported-devices#energy

**Comment by pservais** [comment]
If it's possible 2 widgets would be great. 1 for consumed energy and 1 for produced energy, I think that both in 1 widget is too many data for a widget. The current energy widget is fine, display Cons and Prod, but only the total of usage1 and usage2 should be displayed, same for return1 and 2

**Comment by t0mg** [comment]
2 widgets won't be possible unfortunately, but I agree there is too much data here. Reacticz is designed for mobile devices and small screens, so widgets must be small. That's why I'd rather be scarce and only show partial data here. So what should I focus on ? cons and prod ? the sums of usage and return ?

And don't worry, if you want to be exhaustive and show everything in Reacticz, you can still create a custom text widget :)

**Comment by pservais** [comment]
If a custom text widget is available (loud cheering!) then a widget with Cons and Prod is fine.
You are right, the widgets should stay small.
Isn't it possible to show more info when making the widget bigger, and hiding info when making the widget smaller :D ?

**Comment by t0mg** [comment]
I've just added support for cons and prod data to the standard energy widget, I hope it'll work for you.

Since Reacticz is responsive there is no (simple) way to hide extra information based on the size of the widgets. Besides, I'm rather against the idea of penalizing small screens ;)

The TextWidget is already supported if you want to create some custom output with all the details of your P1 meter, you can give it a try :) In the future we might add customization options (such as icons) to the TextWidget.

Cheers,

**Comment by pservais** [comment]
Nice, thanks! 
Hahaha, the expanding info was just a brainfart. Don't worry this is perfect as it is. 
I can't seem to find the text widget. Where do i create one?

**Comment by t0mg** [comment]
Just create a virtual device of type text in Domoticz. You should then be able to add it in reacticz.

**Comment by pservais** [comment]
Aha, thanks!
