### ISSUE TITLE
iOS caching

### ISSUE THREAD

**Issue by gerard33** [t0mg/reacticz#77]
With #42 I implemented a reload button in the About screen.
Goal was to use it to reload the page on iOS when the app is set to full screen. In that case there is no way to reload the page and due to caching changes will not always be visible.

But I noticed that this doesn't fix the caching issues. In the iOS web app the version is 0.1.6, but if I open the same url on my desktop I am on the latest 0.1.8 version.

I found a solution on this page http://stackoverflow.com/questions/8337631/mobile-web-app-not-clearing-cache-properly.

This means the following line should be added in index.html
`<html manifest="ios.manifest">`

And the following in the ios.manifest file.
`CACHE MANIFEST # Version 0.1.8
NETWORK:
*
CACHE:
index.html`

When there is a new version, the version in the ios.manifest should also be updated.

Anyone here familiar with this and knows if this will work?
I have already tried this over here, but as the app is cached on my iPhone I also cannot test the new version with these additions ;)

**Comment by t0mg** [comment]
Looks like it should work! What if you remove your home screen shortcut and add it again?

**Comment by gerard33** [comment]
I tried that but that didn't work. The caching is quite persistent.
I will do some more testing.

**Comment by t0mg** [comment]
Yeah I realized that when reading the stackoverflow article. What puzzles me is that reacticz doesn't even have an app cache manifest. It's not meant to work offline because that defeats the very purpose of controlling your network :) Each build generates js and css files with different names to avoid such caching issues. It's really strange. Are you using the public server or a locally hosted one? If it's a local server, maybe you should look into the cache policy that's set up (cache-control headers sent by the server tell the browser how long they should keep the file).

**Comment by gerard33** [comment]
I am using a local server (Ubuntu server 14.04 with Apache). I also tried with .htaccess file to disable the caching but that didn't work. 
I am doing some tests right now and it seems to be working now. Small textual changes to AboutView.js are directly visible. Will do some more checks tomorrow.

**Comment by t0mg** [comment]
Fixed in #81
