### ISSUE TITLE
Switch between layouts

### ISSUE THREAD

**Issue by davidlb** [t0mg/reacticz#87]
To be able to create new layout (using # in the url) is really a great feature!

What would be awesome would be to switch between layouts directly by swiping in the app (ie: with this component: https://github.com/oliviertassinari/react-swipeable-views)

Unfortunately, I'm not yet enough skilled in react to do it :(

**Comment by t0mg** [comment]
That would be the next logical step, yes. It's a pretty big change though because it means we'd need more than one layout in the same app. Right now there always is one single dashboard in the app. If you switch to ?2, we still load one single dashboard (but a different one). Having this swiping behavior means that we'd have all dashboards loaded in parallel in the app state. We must be careful not to impact performance (memory footprint, rendering speed, etc). For example the widgets should probably not be rendered during swipe. Pretty large change for the benefit IMO, feel free to give it a shot but it's probably gonna be a little tricky to get it right.

**Comment by davidlb** [comment]
The main idea is there but the UX needs more work. This afternoon,  I should have free time.

**Comment by t0mg** [comment]
Phew, it's finally done. Closing! For further UX improvements feel free to open new issues :)
