### ISSUE TITLE
Reload button on dashboard #2

### ISSUE THREAD

**Issue by gerard33** [t0mg/reacticz#90]
The reload button is not working as it should on iOS in dashboard other then #1 --> in that case it opens in a new safari browser.
See #84: replace the link in the reload button with a reload() JS call.

**Comment by gerard33** [comment]
@t0mg, if you can let me know what I need to change in the code, I can test this on my iPhone to see if that works.

**Comment by t0mg** [comment]
Actually I think you should hold on with this. @davidlb is working on in-app layout switching and once it's done I'll probably remove the url parameter altogether since it complicates things on iOS.

I would also like to remove the appcache manifest. It causes a white screen on Android whenever I update the public server, I need to do a pull-to-refesh.

**Comment by gerard33** [comment]
That makes sense.

Regarding the appcache manifest, I will do some googling on it.
Worst case it will mean I have to add it myself locally before doing 'npm run build'. For me that's no problem is it fixes the caching issue I had before this change.

**Comment by gerard33** [comment]
Will close this issue as it is no longer there due to the new dashboard layout.

**Comment by t0mg** [comment]
Hey @gerard33, did you find anything interesting regarding the appcache manifest thing?
I'd really like to find a way to avoid it because it causes me trouble on Android... and if it's possible I'd like to do so before releasing a new build package [there](https://github.com/t0mg/reacticz/releases).

Thanks!

**Comment by gerard33** [comment]
@t0mg, I found something which I will try this evening.
